manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: mrbanh
      url-base: https://github.com/MrBanh
    - name: kurmangaliyev-a
      url-base: https://github.com/kurmangaliyev-a
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3.0
      import: app/west.yml
    - name: nice-view-bongo-cat
      remote: mrbanh
      revision: main
    - name: zmk-nice-view-java
      remote: kurmangaliyev-a
      revision: main
  self:
    path: config
